### ISSUE TITLE
For discussion: Organize document by subject

### ISSUE THREAD

**Issue by MarcusE1W** [LightTable/user-guide#2]
Hi

In the current documentation some subjects like how to deal with Clojure or javascript can be found in several documents.
I would suggest to consolidate this a bit move the description for oone subject together. It would make it easier to write more documentation if there is a certain flow to the text.

I have started a sample in a branch of my fork:
https://github.com/MarcusE1W/user-guide/tree/toc-org/neworg/

Here  chapters for workflows for clojure, javascript and python have been consolidated from some other text snippets.
This is currently mostly done by linking files into other files but if thereis interest we can merge files together.

Is this a good way forward?

**Comment by sbauer322** [comment]
I think this is worthwhile! The main document should focus on Light Table and the Clojure plugin. 

Support for the Javascript and Python plugins has been minimal as of late and intermingling the three, as we have done occasionally, is not ideal.

**Comment by MarcusE1W** [comment]
I would suggest a top level structure similar to this. The bullet points are to indicate the content, not necessarily sub-levels:
### Introduction
- What is LightTable aimed at.
- The strongest abilities of LightTable.
### Quick Start
- Quick installtation
- Load, save, the various views, useful keymappings
### Installation
- Linux
- Mac
- PC
### Basic functionality
- open, close, search, all the views and their functionality explained, use of the existiong gifs or create new ones etc..
### Advanced functionality
- Plugin manager, search, find, text folding, compleate list of standard commands and what they do, etc..
### Configuration
- Behaviour setting, many examples,
- Keymapping, many examples
### How to use XXX language with LightTable (a suggestion for a better phrase would be welcome)
- Clojure
- Javascript
- Python
- Elm _(Short introduction and link to Rundis official documentation)_
- Markdown
- etc _(happy to check the plugin list and see what docu is given on their respective github pages)_
### References
- Common Terms
- Complete list of standard commands and what they do
- Complete list of all standard behaviours and what they do

If the structure is ok I can move the existing content into the new structure.
The next step would be to make the content of each chapter more consistent and rounded
After that new content can be added.

Is that ok?

**Comment by sbauer322** [comment]
I think this outline should be suitable and a good improvement.

More of an open ended question that does not need to be answered right now, but for the "How to use XXX language with LightTable" section, perhaps it would make sense to create other separate guides for each plugin and simply link to them?

In any case, we certainly should separate the plugin specific content as you suggested.
