### ISSUE TITLE
Hyperlinks of "For Vim Users" and "For Emacs Users" interchanged.

### ISSUE THREAD

**Issue by Pranav2612000** [LightTable/user-guide#3]
Reproduction of this issue:
1) Go to [https://lighttable.gitbooks.io/light-table-user-guide/content/quick_start.html](https://lighttable.gitbooks.io/light-table-user-guide/content/quick_start.html)
2) Scroll to "New Users" heading
3) Hyperlinks of "For Vim Users" and "For Emacs Users" are interchanged i.e "For Vim Users" redirects to the page intended for emacs users and vice versa

If required I am interested in fixing this issue too.

**Comment by prertik** [comment]
Sure @Pranav2612000. Go ahead, if you want to fix this.

**Comment by Pranav2612000** [comment]
Submitted a fix. Thanks for the opportunity. Would like to help more too.

**Comment by prertik** [comment]
Resolved.
